### ISSUE TITLE
Can you give a demo example

### ISSUE THREAD

**Issue by rambleramble** [lorenwel/linefit_ground_segmentation#1]
Would it be possible to share an example with rosbag data to demonstrate this feature?

Thanks!

**Comment by lorenwel** [comment]
Hi @rambleramble. 
Unfortunately I currently don't have time to do that. 
However, usage is pretty simple. There is one topic for point cloud input and two for output of ground points and obstacle points. 
The default parameters should work for most robots that acquire the point cloud fairly close to the ground.
