### ISSUE TITLE
how to run this project with details!

### ISSUE THREAD

**Issue by shqfeng** [lorenwel/linefit_ground_segmentation#20]
excuse me! I am a student, Do you have detailed documents？ thanks！ my email: 2017202140047@whu.edu.cn ，

Looking forward to your reply!

**Comment by lorenwel** [comment]
Hi, 
I added a few more sentences and what needs to be changed to run this pipeline. I hope this will be enough information for people who already know ROS.

**Comment by shqfeng** [comment]
Thanks for your reply！

I had solved this problem several days ago！ Thanks very much！



---Original---
