### ISSUE TITLE
How about the segmentation accuracy and speed for ground object detection?

### ISSUE THREAD

**Issue by deepmeng** [lorenwel/linefit_ground_segmentation#27]
Hi, man, thanks for your work. I just want to know about the segmentation accuracy and speed for your work. Did you ever evaluated it on a public dataset?

**Comment by lorenwel** [comment]
Hi. I never properly evaluated the algorithm. Subjectively, I can tell you that it works on KITTI and runs in real-time on an average CPU. 
I do not have the time to do this evaluation myself, but if you happen to do a more proper investigation I'd be curious about the results.

**Comment by deepmeng** [comment]
Thank you!
