### ISSUE TITLE
Some problems encountered by linefit_ground_segmentation catkin_make

### ISSUE THREAD

**Issue by 798740911** [lorenwel/linefit_ground_segmentation#28]
In the use of linefit_ground_segmentation, the "glog" library cannot be found when performing catkin_make. How can I solve this problem?

**Comment by lorenwel** [comment]
As indicated in the README, this repo depends on [glog_catkin](https://github.com/ethz-asl/glog_catkin.git). You need to have that repo cloned as well. 
In case `glog_catkin` itself fails to build, you should open an issue with them.

**Comment by 798740911** [comment]
Thank you
