### ISSUE TITLE
Compatability with rslidar 16

### ISSUE THREAD

**Issue by HaisenbergPeng** [lorenwel/linefit_ground_segmentation#33]
Dear Author, thanks for sharing your work!
I tried to segment the ground of scanned clouds generated by rslidar16. It is a lot sparser compared to KITTI data. The result is very poor. The white-colored cloud is what is left after segmentation.
![rviz_screenshot_2021_09_22-19_34_50](https://user-images.githubusercontent.com/72208396/134336694-db9d13e3-ec95-4c9f-a66d-9a2a84e9ace6.png)

**Comment by lorenwel** [comment]
The algorithm should work just fine with an rslidar 16. Some parameter changes might help improve performance. Make sure to adjust the `sensor_height` to fit your robot.
