### ISSUE TITLE
HI！

### ISSUE THREAD

**Issue by dong-hub-png** [lorenwel/linefit_ground_segmentation#43]
Hello and thanks for the great work!
May I ask whether the two-point connection is a long straight line in the process of straight line fitting？

**Comment by dong-hub-png** [comment]
Why is this judgment condition set？

**Comment by lorenwel** [comment]
Hi, 

could you please link to the part of the code you are referring to or explain you question in a bit more detail?
At the moment I have trouble understanding your exact issue.

**Comment by lorenwel** [comment]
Please reopen and give more context if your issue persists.
