### ISSUE TITLE
Why is the maximum distance taken here, not the smaller one?

### ISSUE THREAD

**Issue by dong-hub-png** [lorenwel/linefit_ground_segmentation#45]
const double dist_1 = segments_[index_1].verticalDistanceToLine(point_2d.d, point_2d.z);
        const double dist_2 = segments_[index_2].verticalDistanceToLine(point_2d.d, point_2d.z);
        // Select larger distance if both segments return a valid distance.
        if (dist_1 > dist) {
          dist = dist_1;
        }
        if (dist_2 > dist) {
          dist = dist_2;
        }

**Comment by lorenwel** [comment]
Hi, 
good point. That does not really make sense. 
I opened #46 to fix this.
