### ISSUE TITLE
Pkg identifiers in launch files do not match real package names

### ISSUE THREAD

**Issue by YoshuaNava** [lorenwel/linefit_ground_segmentation#8]
The package identifiers from the launchfiles:

https://github.com/lorenwel/linefit_ground_segmentation/blob/11e4ed0090f7637a5929b3c56febe9a6687941ab/linefit_ground_segmentation_ros/launch/segmentation.launch#L6

https://github.com/lorenwel/linefit_ground_segmentation/blob/11e4ed0090f7637a5929b3c56febe9a6687941ab/linefit_ground_segmentation_ros/launch/test.launch#L6

Do not correspond with the real name of this package ROS wrapper:

https://github.com/lorenwel/linefit_ground_segmentation/blob/11e4ed0090f7637a5929b3c56febe9a6687941ab/linefit_ground_segmentation_ros/package.xml#L3

I have submitted a pull request to fix this, #9

**Comment by lorenwel** [comment]
This was on oversight when open-sourcing the package. 
Thanks for the fix!
